name: Deploy MyST Paper

on:
  workflow_call:
    inputs:
      paper-environment-file:
        description: "Name of the paper-specific environment file (optional)"
        required: false
        type: string
        default: "paper-environment.yml"
      base_url:
        description: "Determines where the website is served from, including CSS & JS assets (needed for MyST)"
        required: false
        type: string
        default: "/${{ github.event.repository.name }}"

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    uses: impact-scholars/isp-actions-config/.github/workflows/build-paper.yml@v0.1.0
    with:
      paper-environment-file: ${{ inputs.paper-environment-file }}
      base_url: ${{ inputs.base_url }}

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Download paper build artifact
        uses: actions/download-artifact@v4
        with:
          name: paper-build
          path: _build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
